# Python Hackathon Questions 31 to 40

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
Patients =pd.read_excel("HospitalDatabase.xlsx", sheet_name= "Patients")
EDVisits =pd.read_excel("HospitalDatabase.xlsx", sheet_name= "EDVisits")
AmbulatoryVisits =pd.read_excel("HospitalDatabase.xlsx", sheet_name= "AmbulatoryVisits")
ReAdmissionRegistry =pd.read_excel("HospitalDatabase.xlsx", sheet_name= "ReAdmissionRegistry")
Discharges =pd.read_excel("HospitalDatabase.xlsx", sheet_name= "Discharges")
Providers =pd.read_excel("HospitalDatabase.xlsx", sheet_name= "Providers")
EDUnique = pd.read_excel("HospitalDatabase.xlsx", sheet_name= "EDUnique")

# Q31: Find the count of White Spanish Male.

In [8]:
RaceWhiteGenderMaleLanguageSpanish=(Patients['Race'].str.contains('White'))& (Patients['Gender'].str.contains('Male'))& (Patients['Language'].str.contains('Spanish'))
len(Patients[RaceWhiteGenderMaleLanguageSpanish])

15

# Q32: If patient's gender is Female, add Ms.to the name and for male patients add Mr. to the name.

In [10]:
Patients['FullName']=(Patients['Gender'].str.replace('Male','Mr.').str.replace('Female','Ms.') + ' '+ Patients['FirstName']+ ' ' +Patients['LastName'])
#Patients.head(30)

# Q33: Using a bar chart, which Service had the lowest count of Expected Mortality?

In [16]:
ReAdminService.head(10)
ReAdminService = pd.DataFrame(ReAdminServiceGroup, columns=['Service', 'ExpectedMortality'])
ServiceExpMortalityPlot= ReAdminService["ExpectedMortality"].plot(kind="bar")

NameError: name 'ReAdminService' is not defined

# Q34:  np.arange(1,31).reshape(6,5) Find the array slicing to get the elements with values 11,12,16,17.

In [23]:
arr=np.arange(1,31).reshape(6,5)
#print(arr)
arr1=arr[2,0:2]
arr2=arr[3,0:2]
Newarr=np.hstack((arr1,arr2))
print(Newarr)

[11 12 16 17]


In [24]:
#New Question1... arrange above as 2D 
arr=np.arange(1,31).reshape(6,5)
arr1=arr[2,0:2]
arr2=arr[3,0:2]
Newarr=np.vstack((arr1,arr2))
print(Newarr)

[[11 12]
 [16 17]]


In [25]:
#New question 2: with axis=1
arr=np.arange(1,31).reshape(6,5)
arr1=arr[2,0:2]
arr2=arr[3,0:2]
Newarr=np.stack((arr1,arr2), axis=1)
print(Newarr)

[[11 16]
 [12 17]]


# 35: np.arange(1,31).reshape(6,5), find array slicing for elements 2,8,14,20.

In [27]:
arr=np.arange(1,31).reshape(6,5)
Elements=(arr[0,1], arr[1,2], arr[2,3], arr[3,4])
print(Elements)

(2, 8, 14, 20)


# 36: Create a correlation matrix on EDVisits

# 37: Write a function to print all the upper case letter of a given sentence.

In [5]:
UpperString = input('Enter any string: ')

upper = ''
for char in UpperString:
    if char.isupper():
        upper += char

print('Uppercase characters:', upper)

Enter any string: Home
Uppercase characters: H


# 38: Number of patients on 'Transfer' based on primary diagnosis